### ISSUE TITLE
HTML overriding template doesn't format properly the resulting email

### ISSUE THREAD

**Issue by dpnullvoid** [bugness-chl/sendrecurringinvoicebymail#11]
Hello!
I'm encountering issues while attempting to override the global template. When I paste HTML and select 'Auto-select' or 'HTML', the resulting email doesn't get properly formatted.

![22](https://github.com/bugness-chl/sendrecurringinvoicebymail/assets/108746940/9407348f-47f7-485f-8276-0821b436f475)
 HTML override 

![33](https://github.com/bugness-chl/sendrecurringinvoicebymail/assets/108746940/bc64bd4d-a4a0-4cac-92e7-f4f2d49550e2)
Results

Environment:
Doli 19.0.1 
PHP 8.0.30
Ubuntu 22.04
sendrecurringinvoicebymail 0.3.4
Default mail body's format	-1. (auto-select)

**Comment by AlainRnet** [comment]
Hello. I have the same problem. All HTML code is lost at the time of recording. Line breaks are replaced but the rest is lost (table as in the example above, HTML links, etc.)

Environment:
Doli 17.0.3
PHP 7.4.33
sendrecurringinvoicebymail 0.3.4
Default mail body's format 1. (html)

**Comment by bugness-chl** [comment]
Sorry for the delay, I hoped to fully rewrite the editor but couldn't find the time.

Version [0.3.5](https://github.com/bugness-chl/sendrecurringinvoicebymail/releases/tag/0.3.5) published with a quicker fix for this.

**Comment by AlainRnet** [comment]
Thank you very much, it works fine!
