### ISSUE TITLE
Mail sent not in html

### ISSUE THREAD

**Issue by Support-Green-IT-Solutions** [bugness-chl/sendrecurringinvoicebymail#4]
Hi,

I test your module with mail template in HTML, but mail content received not in HTML.
Possible to have this feature ?
Thanks in advance.

**Comment by Support-Green-IT-Solutions** [comment]
Hi, 

I found how this work : 
In sendrecurringinvoicebymail/class/actions_sendrecurringinvoicebymail.class.php, line 159 : 
`			0,  //msgishtml`
Replace 0 by 1 to send mail in HTML format

Hope this help.

**Comment by bugness-chl** [comment]
Hello,

little ping @Support-Green-IT-Solutions : the new 0.3.2 release brings HTML support, both globally and selectively (template by template).

Tests and reports welcome !
