### ISSUE TITLE
Need to know how we can generate recurring invoice programmatically.

### ISSUE THREAD

**Issue by shineptm** [bugness-chl/sendrecurringinvoicebymail#6]
In Dolibarr, to generate recurring invoice, manually we have to validate a standard invoice and convert it into template invoice.
So will this module do that job. If no then how to achieve that to automate this process programmatically.

**Comment by bugness-chl** [comment]
Note: to manually generate a recurring invoice, you convert a standard one **before** validating it (ie. still at the draft stage).

So your question is how to generate, programmatically, a recurring invoice ? My guess would be to programmatically generate a standard invoice and then use `FactureRec::create()` in `htdocs/compta/facture/class/facture-rec.class.php` : https://github.com/Dolibarr/dolibarr/blob/14.0.0/htdocs/compta/facture/class/facture-rec.class.php#L237 Although doc is lacking, it should be pretty straigthforward (don't forget to delete the standard invoice afterwards, `create()` doesn't seem to do it for you).

And no, this sendrecurringinvoicebymail module doesn't create or even alter much a recurring invoice. It simply hooks itself to the generation process of the offspring invoices.

I'll close the issue. If you need further help, you should go to the dedicated forums https://www.dolibarr.org/#community or contact some professionals : https://wiki.dolibarr.org/index.php/List_of_Dolibarr_partners_and_providers (including [my enterprise](https://www.xlii.si/)).
